# Generated by Django 5.0.2 on 2024-03-25 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffreDeBillets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Familiale', 'Familiale')], max_length=50)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_ventes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_staff', models.BooleanField(default=False)),
                ('clef_1', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('clef_2', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('offre_de_billets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JO_app.offredebillets')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JO_app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clef_finale', models.CharField(default='default_value', editable=False, max_length=50)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('offre_de_billets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JO_app.offredebillets')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JO_app.reservation')),
            ],
        ),
    ]
