# Generated by Django 5.0.2 on 2024-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JO_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='clef_finale',
            field=models.CharField(default='default_value', editable=False, max_length=100),
        ),
    ]
