# Generated by Django 5.0.2 on 2024-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JO_app', '0008_site_sport_offredebillet_site_offredebillet_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='noms_utilisateurs',
            field=models.JSONField(default=list),
        ),
    ]
