# Generated by Django 5.0.2 on 2024-03-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JO_app', '0002_alter_ticket_clef_finale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OffreDeBillets',
            new_name='OffreDeBillet',
        ),
    ]
