# Generated by Django 5.0.2 on 2024-05-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JO_app', '0005_utilisateur_is_superuser_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='JO_app.reservation'),
        ),
    ]
