# Generated by Django 5.0.2 on 2024-05-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JO_app', '0006_alter_ticket_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_ticket', to='JO_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reservation', to='JO_app.reservation'),
        ),
    ]
